USE [master]
GO

/****** Object:  Database [MedicaDB]    Script Date: 30/07/2015 06:03:23 p. m. ******/
CREATE DATABASE [MedicaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MedicaDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\MedicaDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MedicaDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\MedicaDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MedicaDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MedicaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MedicaDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MedicaDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MedicaDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MedicaDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MedicaDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MedicaDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MedicaDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MedicaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MedicaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MedicaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MedicaDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MedicaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MedicaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MedicaDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MedicaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MedicaDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MedicaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MedicaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MedicaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MedicaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MedicaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MedicaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MedicaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MedicaDB] SET RECOVERY FULL 
GO

ALTER DATABASE [MedicaDB] SET  MULTI_USER 
GO

ALTER DATABASE [MedicaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MedicaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MedicaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MedicaDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MedicaDB] SET  READ_WRITE 
GO

